{% set name = "matlab-libs" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: matlab-libs-win.zip                                                          # [win]
  url: https://sourceforge.net/projects/tigl/files/Thirdparty/matlab-libs-win.zip  # [win]

build:
  number: 0
  script:                                                  # [win]
      - mkdir %LIBRARY_PREFIX%\share\matlab\extern         # [win]
      - robocopy /E extern %LIBRARY_PREFIX%\share\matlab\extern || goto :eof     # [win]


about:
  home: https://www.mathworks.com/products/matlab.html
  summary: Basic matlab libraries to create matlab extensions


extra:
  recipe-maintainers:
    - rainman110
