package:
  name: oce
  version: 0.16.1

source:
  fn: OCE-0.16.1.tar.gz
  url: https://github.com/tpaviot/oce/archive/OCE-0.16.1.tar.gz
  patches:
    - fix_tkopengl_dll_path.patch [win]
    - oce-nullrefs-fix.patch
    - oce-fix-msvc2015.patch

build:
  detect_binary_files_with_prefix: True
  number: 11
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - patch             [win]
    - gl2ps
    - freeimageplus
    - tbb
    - python
    - freetype
    - cmake
    - gcc [linux]

  run:
    - gl2ps
    - freeimageplus
    - tbb
    - freetype

about:
  home: https://github.com/tpaviot/oce
  license: LGPL
  summary: OpenCASCADE community edition
