version: '{build}'

os: Visual Studio 2015

environment:
  ANACONDA_API_TOKEN:
    secure: txNQyJOQuWpmZQ2y5KsOOTNixTDsToo/A75izbYNmbT0CGHXEEeeE6fyupsTYZWV

  matrix:
    # - PYTHON_VERSION: "3.5"
    #   PYTHON_ARCH: "32"
    #   CONDA_PY: "35"
    #   CONDA_NPY: "18"
    #   CONDA_INSTALL_LOCN: "C:\\Miniconda35"
    # - PYTHON_VERSION: "3.5"
    #   PYTHON_ARCH: "64"
    #   CONDA_PY: "35"
    #   CONDA_NPY: "18"
    #   CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      CONDA_PY: "36"
      CONDA_NPY: "18"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_NPY: "18"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "37"
      CONDA_NPY: "18"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CONDA_NPY: "18"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"

build:
  parallel: true
  verbosity: quiet

matrix:
  fast_finish: false

install:
  - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda config --set show_channel_urls true
  - cmd: conda install --yes conda-build=3.18.9 anaconda-client gitpython
  - cmd: conda config --add channels dlr-sc
  - cmd: conda config --add channels dlr-sc/label/tigl-dev
  - cmd: set PYTHONUNBUFFERED=1


build_script:
  - python build_recipes.py

