{% set version = "1.1.43" %}

package:
  name: libxslt-static
  version: {{ version }}

source:
  fn: libxslt-{{ version }}.tar.gz
  url: http://xmlsoft.org/sources/libxslt-{{ version }}.tar.gz


build:
  number: 6

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - libxml2-static ==2.14.5

  run:
    - libxml2-static ==2.14.5

about:
  home: http://xmlsoft.org/XSLT/
  summary: The XSLT C library for GNOME
