{% set version = "1.1.43" %}

package:
  name: libxslt-static
  version: {{ version }}

source:
  fn: libxslt-{{ version }}.tar.gz
  url: https://download.gnome.org/sources/libxslt/1.1/libxslt-{{ version }}.tar.xz


build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - gnuconfig  # [unix]
    - pkg-config  # [osx]
    - make # [osx]

  host:
    - libxml2-static ==2.14.5

  run:
    - libxml2-static ==2.14.5

about:
  home: http://xmlsoft.org/XSLT/
  summary: The XSLT C library for GNOME
