{% set version = "0.17.2" %}

package:
  name: oce
  version: {{ version }}

source:
  fn: OCE-{{ version }}.tar.gz
  url: https://github.com/tpaviot/oce/archive/OCE-{{ version }}.tar.gz
  patches:
    - fix_tkopengl_dll_path.patch     # [win]
    - vtk63.patch
    - dlr-feature-coons_c2.patch
    - fix-tiglviewer-selection.patch
    - glibc.patch                     # [linux]

build:
  detect_binary_files_with_prefix: True
  number: 2
  features:
    - vc9              # [win and py27]
    - vc10             # [win and py34]
    - vc14             # [win and py35]

requirements:
  build:
    - patch            # [win]
    - gl2ps
    - freeimageplus
    - tbb
    - python
    - freetype
    - vtk >=6.3.0
    - cmake
    - gcc              # [linux]

  run:
    - gl2ps
    - freeimageplus
    - tbb
    - freetype
    - vtk >=6.3.0

about:
  home: https://github.com/tpaviot/oce
  license: LGPL
  summary: OpenCASCADE community edition
