{% set version = "0.17.2" %}

package:
  name: oce
  version: {{ version }}

source:
  fn: OCE-{{ version }}.tar.gz
  url: https://github.com/tpaviot/oce/archive/OCE-{{ version }}.tar.gz
  md5: bf2226be4cd192606af677cf178088e5
  patches:
    - fix_tkopengl_dll_path.patch     # [win]
    - dlr-feature-coons_c2.patch
    - fix-tiglviewer-selection.patch
    - fix-fonts.patch
    - fix-geomapi_extremacurvecurve.patch
    - fix_time_osx.patch              # [osx]

build:
  detect_binary_files_with_prefix: True
  number: 10


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - patch            # [win]
    - cmake
    - ninja

  host:
    - libglu
    - gl2ps
    - freeimageplus
    - tbb
    - python
    - freetype

  run:
    - gl2ps
    - freeimageplus
    - tbb
    - freetype

about:
  home: https://github.com/tpaviot/oce
  license: LGPL
  summary: OpenCASCADE community edition
