{% set version = "7.6.2" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  git_url: https://github.com/tpaviot/pythonocc-core.git
  git_tag: {{ version }}
  patches:
    - 0001-DLR-patch-to-support-c2-continous-coons-patches.patch

build:
  number: 1
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - ninja
    - cmake
    - swig >=4.0.2

  host:
    - python {{ python }}
    - opencascade ==7.6.2

  run:
    - opencascade ==7.6.2
    - python

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: A python wrapper for the OCE library
