{% set version = "0.17.3" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  fn: pythonocc-core-{{ version }}.tar.gz
  url: https://github.com/tpaviot/pythonocc-core/archive/{{ version }}.tar.gz
  patches:
    - pyocc_coons_c2.patch
    - link_python.patch
    - jupyter-renderer.patch

build:
  number: 7
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - ninja
    - python
    - cmake
    - swig >=3.0.11
    - m2-patch [win]

  host:
    - python
    - libglu [linux]
    - oce ==0.17.2

  run:
    - libglu [linux]
    - pyqt
    - oce ==0.17.2
    - python

test:
  imports:
    - OCC
    - OCC.BRepPrimAPI

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: A python wrapper for the OCE library
