{% set version = "0.17" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  fn: pythonocc-core-{{ version }}.tar.gz
  url: https://github.com/tpaviot/pythonocc-core/archive/{{ version }}.tar.gz
  patches:
    - fix_graphicshr_location.patch     # [win]
    - pyocc_coons_c2.patch
    - fixmemcpy.patch # [linux]
    - link_python.patch
    - jupyter-renderer.patch

build:
  number: 4
  binary_relocation: false [osx]
  features:
    - vc9               # [win and py27]
    - vc10              # [win and py34]
    - vc14              # [win and py35]

requirements:
  build:
    - ninja
    - python
    - oce ==0.17.2
    - cmake
    - swig >=3.0.9
    - patch [win]

  run:
    - pyqt
    - oce ==0.17.2
    - python

test:
  imports:
    - OCC
    - OCC.BRepPrimAPI

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: A python wrapper for the OCE library
