{% set version = "1.10.2" %}

package:
  name: ninja
  version: {{ version }}

source:
  fn: ninja-{{ version }}.tar.gz
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz

build:
  number: 0
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - python
    - gcc [linux]

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  summary: A small build system with a focus on speed.
