package:
  name: swig
  version: 3.0.12

source:
  fn: swigwin-3.0.12.zip [win]
  url: http://prdownloads.sourceforge.net/swig/swigwin-3.0.12.zip [win]
  fn: swig-3.0.12.tar.gz   [unix]
  url: http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz   [unix]

build:
  number: 1
  detect_binary_files_with_prefix: True    [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - pcre      [unix]
    - python    [unix]
  run:
    - pcre      [unix]

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
    summary: Simplified Wrapper Interface Generator
