package:
  name: swig
  version: 2.0.10

source:
  fn: swigwin-2.0.10.zip
  url: https://sourceforge.net/projects/swig/files/swigwin/swigwin-2.0.10/swigwin-2.0.10.zip/download

test:
  commands:
    - swig -help

about:
    home: http://www.swig.org/
    license: GPLv3
    summary: Simplified Wrapper Interface Generator
