{% set version = "2.6.5" %}

package:
  name: freetype-static
  version: {{ version }}

source:
  fn: freetype-{{ version }}.tar.gz
  url: https://download-mirror.savannah.gnu.org/releases/freetype/freetype-old/freetype-{{ version }}.tar.bz2
  md5: 6a386964e18ba28cb93370e57a19031b

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja
    - python
    - bzip2 [linux]


about:
  home: http://www.freetype.org/
  license: GNU GPL Version 2 and FreeType License
  summary: FreeType is a freely available software library to render fonts
