{% set version = "2.6.5" %}

package:
  name: freetype-static
  version: {{ version }}

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-{{ version }}.tar.gz
  sha256: 174d9e53402e1bf9ec7277e22ec199ba3e55a6be2c0740cb18c0ee9850fc8c34

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja


about:
  home: http://www.freetype.org/
  license: GNU GPL Version 2 and FreeType License
  summary: FreeType is a freely available software library to render fonts
