{% set version = "2.14.1" %}

package:
  name: freetype-static
  version: {{ version }}

source:
  fn: freetype-{{ version }}.tar.gz
  url: https://sourceforge.net/projects/freetype/files/freetype2/{{ version }}/freetype-{{ version }}.tar.gz/download
  md5: d8c8b0c3a6d4c7ed4c90e1a8c7171887

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja
    - python


about:
  home: http://www.freetype.org/
  license: GNU GPL Version 2 and FreeType License
  summary: FreeType is a freely available software library to render fonts
