{% set version = "3.0.0rc1" %}

package:
  name: tigl3
  version: {{ version }}

source:
  git_url: https://github.com/DLR-SC/tigl.git
  git_tag: cpacs_3

build:
  number: 10
  features:
    - vc9               # [win and py27]
    - vc10              # [win and py34]
    - vc14              # [win and py35]

requirements:
  build:
    - tixi3 >=3.0.3
    - ninja
    - python
    - oce ==0.17.2
    - pythonocc-core ==0.17
    - cmake
    - swig =3.0.9
    - doxygen

  run:
    - tixi3 >=3.0.3
    - pyqt
    - oce ==0.17.2
    - pythonocc-core ==0.17
    - python

test:
  imports:
    - tigl3.tigl3wrapper
    - tigl3.geometry

about:
  home: https://github.com/DLR-SC/tigl
  license: Apache 2.0
  summary: The TiGL Geometry Library to process aircraft geometries in pre-design
