{% set version = "3.4.0" %}

package:
  name: tigl3
  version: {{ version }}

source:
  git_url: https://github.com/DLR-SC/tigl.git
  git_tag: v{{ version }}

build:
  number: 0


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libselinux') }}           # [linux]
    - {{ cdt('libXdamage') }}           # [linux]
    - {{ cdt('libXfixes') }}            # [linux]
    - {{ cdt('libXxf86vm') }}           # [linux]
    - ninja
    - cmake
    - swig >=3.0.11
    - doxygen

  host:
    - tixi3 ==3.3.0
    - opencascade ==7.4.0
    - pythonocc-core ==7.4.1
    - tbb-devel ==2019.5
    - python {{ python }}
    - libglu                            # [linux]
    - qt==5.15.7

  run:
    - tixi3 ==3.3.0
    - pyqt
    - opencascade ==7.4.0
    - pythonocc-core ==7.4.1
    - tbb ==2019.5
    - python

test:
  imports:
    - tigl3.tigl3wrapper
    - tigl3.geometry
    - tigl3.surface_factories

about:
  home: https://github.com/DLR-SC/tigl
  license: Apache 2.0
  summary: The TiGL Geometry Library to process aircraft geometries in pre-design
