{% set version = "3.4.1+daha96_1037fix" %}

package:
  name: tigl3
  version: {{ version }}

source:
  git_url: https://github.com/daha96/tigl.git
  git_branch: 1037-fix-new-rebased

build:
  number: 22


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - ninja
    - cmake
    - swig >=3.0.11
    - doxygen

  host:
    - tixi3 ==3.3.0
    - opencascade ==7.4.0
    - pythonocc-core ==7.4.1
    - tbb-devel ==2019.5
    - python {{ python }}

  run:
    - tixi3 ==3.3.0
    - pyqt
    - opencascade ==7.4.0
    - pythonocc-core ==7.4.1
    - tbb ==2019.5
    - python

test:
  imports:
    - tigl3.tigl3wrapper
    - tigl3.geometry
    - tigl3.surface_factories

about:
  home: https://github.com/DLR-SC/tigl
  license: Apache 2.0
  summary: The TiGL Geometry Library to process aircraft geometries in pre-design
