{% set version = "3.5.0" %}
{% set occt_version = "7.9.3" %}

package:
  name: tigl3
  version: {{ version }}

source:
  - url: https://github.com/DLR-SC/tigl/archive/v{{ version }}.tar.gz
    sha256: 2f2161d3b623a9bb6b113ebabe23f028ba5fa3eb6d9be914b59ba2c3e0d724d7
    patches:
      - patches/fix-python-site-packages-detection.patch
  - url: https://github.com/tpaviot/pythonocc-core/archive/{{ occt_version }}.tar.gz
    sha256: a25e3d136267271abfc71b35dd4b6d0cda65964fb3a69a0b4b7712681113e9a6
    folder: thirdparty/pythonocc-core

build:
  number: 0


requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libselinux') }}           # [linux]
    - {{ cdt('libXdamage') }}           # [linux]
    - {{ cdt('libXfixes') }}            # [linux]
    - {{ cdt('libXxf86vm') }}           # [linux]
    - ninja >=1.10.0
    - cmake >=3.11
    - swig 4.4.*
    - doxygen ==1.13.2

  host:
    - tixi ==3.3.2
    - occt =={{ occt_version }} *novtk*
    - pythonocc-core =={{ occt_version }} *novtk*
    - python {{ python }}
    - libglu                            # [linux]
    - qt ==5.15.15

  run:
    - tixi ==3.3.2
    - occt =={{ occt_version }} *novtk*
    - pythonocc-core =={{ occt_version }} *novtk*
    - python {{ python }}
    - qt ==5.15.15
    - pyqt

test:
  imports:
    - tigl3.tigl3wrapper
    - tigl3.geometry
    - tigl3.surface_factories

about:
  home: https://github.com/DLR-SC/tigl
  license: Apache 2.0
  summary: The TiGL Geometry Library to process aircraft geometries in pre-design

