package:
  name: gl2ps
  version: 1.3.8

source:
  fn: new-bundle.zip [win]
  url: https://github.com/QbProg/oce-win-bundle/archive/qb/new-bundle.zip [win]
  fn: gl2ps-1.3.8.tgz [unix]
  url: http://geuz.org/gl2ps/src/gl2ps-1.3.8.tgz [unix]
  patches:
    - installdir.patch  [win]

build:
  number: 4
  binary_relocation: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - patch                             # [win]
    - cmake

  host:
    - zlib             # [unix]

  run:
    - zlib             # [unix]


about:
  home: http://www.geuz.org/gl2ps/
  license: GNU LPGL Version 2
  summary: GL2PS, an OpenGL to PostScript printing library
