package:
  name: libxslt
  version: 1.1.29

source:
  fn: libxslt-1.1.29.tar.gz
  url: ftp://xmlsoft.org/libxslt/libxslt-1.1.29.tar.gz


build:
  number: 1
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - python
    - libxml2
    - gcc               [linux]

  run:
    - libxml2

about:
  home: http://xmlsoft.org/XSLT/
  summary: The XSLT C library for GNOME
