{% set version = "1.1.43" %}

package:
  name: libxslt
  version: {{ version }}

source:
  fn: libxslt-{{ version }}.tar.gz
  url: http://xmlsoft.org/sources/libxslt-{{ version }}.tar.gz
  patches:
   - fixmemcpy.patch


build:
  number: 2

requirements:
  build:
    - python
    - libxml2
    - gcc               [linux]

  run:
    - libxml2

about:
  home: http://xmlsoft.org/XSLT/
  summary: The XSLT C library for GNOME
