{% set version = "1.1.0" %}
{% set sha256 = "209bad1c665d73464aff393ed2939d38d7fc23d20407629bfadef82480d3681a" %}

package:
    name: pythreejs
    version: {{ version }}

source:
    fn: pythreejs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pythreejs/pythreejs-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 3
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - pip
        - python
        - setuptools
        - nodejs
    run:
        - python
        - ipywidgets >=7,<8
        - numpy
        - traittypes
        - ipydatawidgets

test:
    imports:
        - pythreejs

about:
    home: https://github.com/jovyan/pythreejs
    license: BSD 3-Clause
    summary: A Python / ThreeJS bridge utilizing the Jupyter widget infrastructure.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - vidartf
