package:
  name: libxml2-static
  version: 2.14.5

source:
  fn: libxml2-v2.14.5.tar.gz
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.14.5/libxml2-v2.14.5.tar.gz
  md5: 2da0f9e59d6ce8d4f9d8460a8341b135

build:
  number: 3

requirements:
  build:
    - autoconf          # [osx]
    - automake          # [osx]
    - libtool           # [osx]
    - pkg-config        # [osx]
    - {{ compiler('c') }}
about:
  home: http://www.xmlsoft.org/
  summary: The XML C parser and toolkit of Gnome