mkdir buildd
cd buildd

cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=$PREFIX \
 -DCMAKE_BUILD_TYPE=Release \
 -DCMAKE_PREFIX_PATH=$PREFIX \
 -DCMAKE_SYSTEM_PREFIX_PATH=$PREFIX \
 -DFT_DISABLE_PNG=TRUE \
 -DFT_DISABLE_ZLIB=TRUE \
 -DFT_DISABLE_BZIP2=TRUE \
 -DFT_DISABLE_HARFBUZZ=TRUE \
 -DFT_DISABLE_BROTLI=TRUE \
 ..

ninja

ninja install

