package:
  name: freetype
  version: 2.14.1

source:
  fn: freetype-2.14.1.tar.gz
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.14.1.tar.gz
  md5: 6a386964e18ba28cb93370e57a19031b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja


about:
  home: http://www.freetype.org/
  license: GNU GPL Version 2 and FreeType License
  summary: FreeType is a freely available software library to render fonts
