package:
  name: freetype
  version: 2.14.1

source:
  fn: freetype-2.14.1.tar.gz
  url: https://sourceforge.net/projects/freetype/files/freetype2/2.14.1/freetype-2.14.1.tar.gz/download
  md5: d8c8b0c3a6d4c7ed4c90e1a8c7171887

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja


about:
  home: http://www.freetype.org/
  license: GNU GPL Version 2 and FreeType License
  summary: FreeType is a freely available software library to render fonts
