package:
  name: freetype
  version: 2.6.0

source:
  fn: freetype-2.6.tar.gz
  url: http://download.savannah.gnu.org/releases/freetype/freetype-2.6.tar.gz

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - cmake


about:
  home: http://www.freetype.org/
  license: GNU GPL Version 2 and FreeType License
  summary: FreeType is a freely available software library to render fonts
