package:
  name: freetype
  version: 2.6.5

source:
  fn: freetype-2.6.5.tar.bz2
  url: https://sourceforge.net/projects/freetype/files/freetype2/2.6.5/freetype-2.6.5.tar.bz2/download
  md5: 6a386964e18ba28cb93370e57a19031b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja


about:
  home: http://www.freetype.org/
  license: GNU GPL Version 2 and FreeType License
  summary: FreeType is a freely available software library to render fonts
