{% set version = "2.2.3" %}

package:
  name: tigl
  version: {{ version }}

source:
  fn: tigl-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tigl/archive/v{{ version }}.tar.gz
  patches:
    - fixmemcpy.patch   # [linux]

build:
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - ninja
    - python {{ python }} 
    - cmake
    - swig >=3.0.11
    - doxygen

  host:
    - tixi ==2.2.4
    - oce ==0.17.2
    - pythonocc-core ==0.17.3
    - python {{ python }}

  run:
    - tixi ==2.2.4
    - pyqt
    - oce ==0.17.2
    - pythonocc-core ==0.17.3
    - python {{ python }}

test:
  imports:
    - tigl.tiglwrapper
    - tigl.geometry

about:
  home: https://github.com/DLR-SC/tigl
  license: Apache 2.0
  summary: The TiGL Geometry Library to process aircraft geometries in pre-design
