{% set version = "2.2.2" %}

package:
  name: tigl
  version: {{ version }}

source:
  fn: tigl-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tigl/archive/v{{ version }}.tar.gz
  patches:
    - fix-exports.patch

build:
  number: 0
  features:
    - vc9               # [win and py27]
    - vc10              # [win and py34]
    - vc14              # [win and py35]

requirements:
  build:
    - tixi ==2.2.4
    - ninja
    - python
    - oce ==0.17.2
    - pythonocc-core ==0.17
    - cmake
    - swig >=3.0.9
    - doxygen

  run:
    - tixi ==2.2.4
    - pyqt
    - oce ==0.17.2
    - pythonocc-core ==0.17
    - python

test:
  imports:
    - tigl.tiglwrapper
    - tigl.geometry

about:
  home: https://github.com/DLR-SC/tigl
  license: Apache 2.0
  summary: The TiGL Geometry Library to process aircraft geometries in pre-design
