{% set version = "3.1.0" %}

package:
  name: tixi3
  version: {{ version }}

source:
  fn: tixi-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tixi/archive/v{{ version }}.tar.gz
  md5: ab85e8484c6f153f5ecf49da512fece3
  patches:
    - disable-fortran.patch

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - doxygen >=1.8.10
    - cmake   >=3.0.0

  host:
    - python {{ python }}
    - curl-static ==7.50.3
    - libxml2-static ==2.9.3
    - libxslt-static ==1.1.29

  run:
    - python

test:
    commands:
    - tixiDemo

about:
  home: https://github.com/DLR-SC/tixi
  license: Apache 2.0
  summary: Fast and simple XML interface library
