{% set version = "3.3.1" %}

package:
  name: tixi3
  version: {{ version }}

source:
  fn: tixi-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tixi/archive/v{{ version }}.tar.gz
  md5: d4e76a0bbc79445016bec8470833b0c3
  patches:
    - disabled-fortran-example.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - doxygen >=1.8.10
    - cmake   >=3.0.0

  host:
    - python {{ python }}
    - curl-static ==7.50.3
    - libxml2-static ==2.14.5
    - libxslt-static ==1.1.43

  run:
    - python

test:
    commands:
    - tixiDemo

about:
  home: https://github.com/DLR-SC/tixi
  license: Apache 2.0
  summary: Fast and simple XML interface library
