{% set version = "2.2.4" %}

package:
  name: tixi
  version: {{ version }}

source:
  fn: tixi-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tixi/archive/v{{ version }}.tar.gz
  md5: 4db741d2deebb55f3fa5fdbc057dad81
  patches:
    - install.patch
    - fixmemcpy.patch  # [linux]
    - private_linking.patch

build:
  number: 9

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - doxygen >=1.8.10

  host:
    - curl-static ==7.50.3
    - libxml2-static ==2.9.3
    - libxslt-static ==1.1.29
    - python {{ python }}
  
  run:
    - python

test:
    commands:
    - tixiDemo

about:
  home: https://github.com/DLR-SC/tixi
  license: Apache 2.0
  summary: Fast and simple XML interface library
