package:
  name: tixi
  version: 2.2.3

source:
  fn: tixi-2.2.3.tar.gz
  url: https://github.com/DLR-SC/tixi/archive/v2.2.3.tar.gz

build:
  features:
    - vc9               [win and py27]

requirements:
  build:
    - python
    - curl
    - libxml2
    - libxslt

about:
  home: https://github.com/DLR-SC/tixi
  license: Apache 2.0
  summary: Fast and simple XML interface library