{% set version = "2.2.4" %}

package:
  name: tixi
  version: {{ version }}

source:
  fn: tixi-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tixi/archive/v{{ version }}.tar.gz
  patches:
    - install.patch
    - fixmemcpy.patch

build:
  number: 3
  features:
    - vc9              # [win and py27]
    - vc10             # [win and py34]
    - vc14             # [win and py35]

requirements:
  build:
    - python
    - curl
    - libxml2
    - libxslt
    - gcc               # [linux]

  run:
    - curl              # [unix]
    - libxml2           # [unix]
    - libxslt           # [unix]
    - python 2.7.*      # [py27]
    - python 3.4.*      # [py34]
    - python 3.5.*      # [py35]

test:
  commands:
    - tixiDemo

about:
  home: https://github.com/DLR-SC/tixi
  license: Apache 2.0
  summary: Fast and simple XML interface library
