package:
  name: pythonocc-core
  version: 0.16.3dev

source:
  fn: pythonocc-core-master.zip
  url: https://github.com/tpaviot/pythonocc-core/archive/master.zip
  patches:
    - fix_graphicshr_location.patch

build:
  number: 1
  binary_relocation: true
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - ninja
    - patch             [win]
    - python
    - oce ==0.16.1
    - cmake
    - swig
    - gcc               [linux]

  run:
    - pyqt
    - oce ==0.16.1
    - python

test:
  imports:
    - OCC
    - OCC.BRepPrimAPI

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: A python wrapper for the OCE library
