package:
  name: pythonocc-core
  version: 0.16.3dev

source:
  fn: master.zip
  url: https://github.com/tpaviot/pythonocc-core/archive/master.zip
  patches:
    - fixwindows.patch

build:
  features:
    - vc9               [win and py27]

requirements:
  build:
    - ninja
    - patch
    - python
    - oce ==0.16.1
    - cmake
    - swig

  run:
    - pyqt
    - oce ==0.16.1
    - python

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: A python wrapper for the OCE library