package:
  name: freeimageplus-static
  version: 3.18.0

source:
  fn: new-bundle.zip [win]
  url: https://github.com/joergbrech/oce-win-bundle/archive/refs/heads/master.zip [win]
  fn: FreeImage3180.zip [unix]
  url: http://downloads.sourceforge.net/freeimage/FreeImage3180.zip [unix]
  patches:
    - installdir.patch   [win]
    - installlinux.patch [linux]

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja


about:
  home: http://freeimage.sourceforge.net/
  license: GNU LPGL Version 2 and FreeImage Public License
  summary: FreeImage, The productivity booster
