package:
  name: freeimageplus-static
  version: 3.18.0

source:
  fn: new-bundle.zip [win]
  url: https://github.com/QbProg/oce-win-bundle/archive/qb/new-bundle.zip [win]
  fn: FreeImage3180.zip [unix]
  url: http://downloads.sourceforge.net/freeimage/FreeImage3180.zip [unix]
  patches:
    - installdir.patch   [win]
    - installlinux.patch [linux]
    - fix-fp_h-not-found.patch [osx]
    - fix-macos-macros.patch [osx]
    - Imath_dynamic_exceptions.patch

build:
  number: 6

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja


about:
  home: http://freeimage.sourceforge.net/
  license: GNU LPGL Version 2 and FreeImage Public License
  summary: FreeImage, The productivity booster
