{% set version = "0.1" %}

package:
  name: cpacscreator
  version: {{ version }}

source:
  git_url: https://github.com/cfsengineering/TiglCreator.git
  git_tag: creator_pre_release

build:
  number: 1


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('libxcb') }}               # [linux]
    - {{ cdt('libxi-devel') }}          # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - ninja
    - python
    - cmake
    - swig >=3.0.11
    - doxygen

  host:
    - tixi3 >=3.0.3
    - oce ==0.17.2
    - pythonocc-core ==0.17.3
    - python
    - qt

  run:
    - tixi3 >=3.0.3
    - pyqt
    - oce ==0.17.2
    - pythonocc-core ==0.17.3
    - python

test:
  imports:
    - tigl3.tigl3wrapper
    - tigl3.geometry
    - tigl3.surface_factories

about:
  home: https://github.com/DLR-SC/tigl
  license: Apache 2.0
  summary: The TiGL Geometry Library to process aircraft geometries in pre-design
