package:
  name: doxygen
  version: 1.8.15

source:
  fn: doxygen-1.8.15.windows.bin.zip                                             [win32]
  url: http://doxygen.nl/files/doxygen-1.8.15.windows.bin.zip                    [win32]
  fn: doxygen-1.8.15.windows.x64.bin.zip                                         [win64]
  url: http://doxygen.nl/files/doxygen-1.8.15.windows.x64.bin.zip                [win64]
  url: http://doxygen.nl/files/doxygen-1.8.15.src.tar.gz                         [not win]
  fn: /doxygen-1.8.15.src.tar.gz                                                 [not win]

requirements: [not win]
  build:      [not win]
    - cmake   [not win]
    - gcc     [linux]

test:
  commands:
    - doxygen -v

about:
    home: http://www.stack.nl/~dimitri/doxygen/index.html
    license: GPLv3

