{% set version = "3.24.4" %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://gitlab.kitware.com/cmake/cmake/-/archive/v{{ version }}/cmake-v{{ version }}.tar.gz
  sha256: 8280dce0d93117b7a7bf18b2669477c8947d6e9db7dc9281c3de4e7554fd14a0

build:
  number: 1
  # skip: True  # [win and vc<14]
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make            # [unix]

  host:
    - zlib            # [unix]
    - libuv           # [unix]
    - openssl         # [unix]
    - ncurses         # [unix]

  run:
    - zlib            # [unix]
    - libuv           # [unix]
    - openssl         # [unix]
    - ncurses         # [unix]

    - vs2015_runtime  # [win]

test:
  commands:
    - cmake --version
    - ctest --version
    - cpack --version
    - ccmake --version  # [unix]

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  license_file:
    - Copyright.txt
    - Utilities/cmbzip2/LICENSE         # [win]
    - Utilities/cmcurl/COPYING          # [win]
    - Utilities/cmexpat/COPYING         # [win]
    - Utilities/cmliblzma/COPYING       # [win]
    - Utilities/cmzlib/Copyright.txt    # [win]
    - Utilities/cmlibuv/LICENSE         # [win]
    - Utilities/cmlibrhash/COPYING      # [win]
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmjsoncpp/LICENSE
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
