name: Build Conda Packages

on: 
  push:
    branches:
      - '**'
  pull_request: # this should be changed to pull_request_target before merge

 
jobs:

  build-conda-packages:

    strategy:
      fail-fast: false
      matrix:
        arch: ['x86', 'x64']
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: ['3.6', '3.7', '3.8']
        #exclude:
        #  - arch: x86
        #    os: macos-latest
        #  - arch: x86
        #    os: ubuntu-latest
        #    python: 3.8

    runs-on: ${{ matrix.os }}    

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive


    - name: Setup conda
      uses: bryanwweber/setup-miniconda@fix-10
      with:
        auto-update-conda: true
        activate-environment: tigl-conda
        miniconda-version: 'latest'
        architecture: ${{ matrix.arch }}
        python-version: ${{ matrix.python }}
        channels: dlr-sc,dlr-sc/label/tigl-dev

    - name: Install requirements (ubuntu, macos)
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash -l {0}
      run: |
        conda install -y conda-build gitpython anaconda-client mesa-dri-drivers-cos6-x86_64
        conda info -a
        conda list

    - name: Install requirements (windows)
      if: contains(matrix.os, 'windows')
      shell: cmd /C call {0}
      run: |
        conda install -y conda-build=3.18.9 gitpython anaconda-client
        conda info -a
        conda list

    - name: build conda packages
      run: |
        python --version
        python build_recipes.py
 