name: Build Conda Packages

on: 
  push:
    branches:
      - '**'
  pull_request:

env:
  GH_HEAD_REF: ${{ github.head_ref }}
 
jobs:

  build-conda-packages:

    strategy:
      fail-fast: false
      matrix:
        arch: ['x64']
        os: [windows-2022, ubuntu-22.04, macos-13]
        python: ['3.9', '3.10', '3.11', '3.12']
        exclude:
          - arch: x86
            os: macos-latest
          - arch: x86
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}    

    steps:
    - name: Set git to use LF
      run: |
          git config --global core.autocrlf false

    - uses: actions/checkout@v5
      with:
        submodules: recursive
        fetch-depth: 2


    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: tigl-conda
        miniconda-version: 'latest'
        architecture: ${{ matrix.arch }}
        python-version: ${{ matrix.python }}
        channels: dlr-sc,dlr-sc/label/tigl-dev

    - name: Install requirements (ubuntu, macos)
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash -l {0}
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential
        conda install -y conda-build gitpython anaconda-client mesa-dri-drivers-cos6-x86_64
        conda info -a
        conda list
        echo $PATH

    - name: Install requirements (windows)
      if: contains(matrix.os, 'windows')
      shell: cmd /C call {0}
      run: |
        conda install -y conda-build gitpython anaconda-client
        conda info -a
        conda list

    - name: build conda packages
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash -l {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        python --version
        python build_recipes.py

    - name: build conda packages
      if: contains(matrix.os, 'windows')
      shell: cmd /C call {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        python --version
        python build_recipes.py
 
