name: Build Conda Packages

on: 
  push:
    branches:
      - '**'
  pull_request: # this should be changed to pull_request_target before merge

 
jobs:

  build-conda-packages:

    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: [3.6, 3.7, 3.8]
        exclude:
          - arch: x86
            os: macos-latest
          - arch: x86
            os: ubuntu-latest
            python: 3.8

    runs-on: ${{ matrix.os }}    

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    # we need a custom miniconda, at least for the 32 bit builds....

    - name: Set installer url (ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: echo "::set-env name=INSTALLER_URL::https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-${{ matrix.arch }}.sh"

    - name: Set installer url (macos)
      if: contains(matrix.os, 'macos')
      run: echo "::set-env name=INSTALLER_URL::https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-${{ matrix.arch }}.sh"


    - name: Install and setup miniconda (ubuntu, macos)
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      run: |
        wget ${{ env.INSTALLER_URL }} -O miniconda.sh;
        chmod +x miniconda.sh
        yes | ./miniconda.sh -b -p $HOME/miniconda
        echo "::set-env name=PYTHONUNBUFFERED::1"
        echo "::add-path::$HOME/miniconda/bin"
        echo "::add-path::$HOME/miniconda/lib"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda install python=${{ matrix.python }} -c anaconda
        conda install conda-build gitpython anaconda-client mesa-dri-drivers-cos6-x86_64
        conda config --add channels https://conda.anaconda.org/dlr-sc
        conda config --add channels https://conda.anaconda.org/dlr-sc/label/tigl-dev

    - name: Install and setup miniconda (windows)
      if: contains(matrix.os, 'windows')
      run: |
        curl --retry 3 -o miniconda.exe -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-${{matrix.arch}}.exe
        start /wait "" ".\miniconda.exe /S /D=%UserProfile%\Miniconda3" -Wait
        echo "::set-env name=PYTHONUNBUFFERED::1"
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda config --set show_channel_urls true
        conda install python=${{ matrix.python }} -c anaconda
        conda install conda-build=3.18.9 gitpython anaconda-client
        conda config --add channels https://conda.anaconda.org/dlr-sc
        conda config --add channels https://conda.anaconda.org/dlr-sc/label/tigl-dev

    - name: build conda packages
      run: |
        python --version
        python build_recipes.py
 